apiVersion: v1
kind: Service
metadata:
  name: {{ include "rkvd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rkvd.labels" . | nindent 4 }}
spec:
#  clusterIP: None
  type: LoadBalancer
  publishNotReadyAddresses: true
  ports:
    - name: http
      protocol: "TCP"
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
    - name: rpc
      protocol: "TCP"
      port: {{ .Values.rpcPort }}
      targetPort: {{ .Values.rpcPort }}
  selector:
    {{- include "rkvd.selectorLabels" . | nindent 4 }}
