apiVersion: v1
kind: Service
metadata:
  name: {{ include "rkvd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rkvd.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: serf-tcp
      protocol: "TCP"
      port: {{ .Values.serfPort }}
      targetPort: {{ .Values.serfPort }}
    - name: serf-udp
      protocol: "UDP"
      port: {{ .Values.serfPort }}
      targetPort: {{ .Values.serfPort }}
    - name: raft
      protocol: "TCP"
      port: {{ .Values.raftPort }}
      targetPort: {{ .Values.raftPort }}
    - name: rpc
      protocol: "TCP"
      port: {{ .Values.rpcPort }}
      targetPort: {{ .Values.rpcPort }}
    - name: http
      protocol: "TCP"
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
  selector:
    {{- include "rkvd.selectorLabels" . | nindent 4 }}
